# This file holds all of the standard configuration for our development environment

version: '3.7'

services: 
    # SQL DATABASE
    db: 
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: async-await

    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080
    # Backend Application 

    #Frontend Application

volumes:
    myapp: